import numpy as np

N = 50  # Example number of nodes
alpha = 1.0  # Concentration parameter

# Track the number of nodes in each cluster
cluster_counts = []

# Track the specific cluster assignment for each node i
Z = []

for i in range(N):
    # 1. Calculate weights and probabilities
    weights = cluster_counts + [alpha]
    total = sum(weights)
    probabilities = [w / total for w in weights]

    # 2. Make the choice
    # We give choice() a list of indices from 0 up to the number of weights
    options = range(len(weights))
    chosen_index = np.random.choice(options, p=probabilities)

    # 3. Record the assignment for node i
    Z.append(chosen_index)

    # 4. Update the counts for the next node
    if chosen_index == len(cluster_counts):
        # If the index equals the current number of clusters, it's a new table
        cluster_counts.append(1)
    else:
        # Otherwise, add one person to the chosen existing table
        cluster_counts[chosen_index] += 1

# The final number of clusters generated by the CRP
K = len(cluster_counts)

print(f"Generated {K} clusters for {N} nodes.")
print(f"Cluster counts: {cluster_counts}")
print(f"Node assignments (Z): {Z}")


# We set the hyperparameters a and b
a = 1
b = 1

# We define the matrix of theta values, sampled from the beta distribution
theta_matrix = np.random.beta(a, b, size=(K, K))

print(theta_matrix)


# Initialize an empty N x N matrix
X = np.zeros((N, N))

for i in range(N):
    for j in range(N):
        # 1. Look up the probability for this specific pair of nodes
        p_link = theta_matrix[Z[i], Z[j]]

        # 2. Flip the coin! n=1 makes it a simple True/False (1 or 0) outcome
        X[i, j] = np.random.binomial(n=1, p=p_link)

print(X)
